### PR TITLE
change classroom instructions to point to hybrid cloud console and sa…

### PR DESCRIPTION
**Pull request by rsriniva**
…ndbox for both partners and RHT associates

### CODE REVIEW

**Comment by stencell** [comment]
Suggest some small modification like this: 

If you don't already have access to Red Hat OpenShift AI, provision an environment using the [Red Hat Hybrid Cloud Console](https://console.redhat.com/application-services/data-science). The "Try it in the sandbox" option provides free access to a Red Hat OpenShift AI instance useful for experimentation.

The other courses in the learning path use a different classroom. The prerequisites and classroom requirements are listed in the respective individual courses.

**Review by jramcast — APPROVED** [review]
LGTM

**Comment by rsriniva** [comment]
@jramcast - this PR is to make both redhat associates and partners use the sandbox for course 1 for cost reasons. For other courses, we ask partners to provision their own clusters

**Comment by stencell** [comment]
👍🏻

**Review by stencell — APPROVED** [review]

**Pull request merged**
