### PR TITLE
Mention version of RHOAI for lab testing

### PR DESCRIPTION
**Pull request by rsriniva**

### CODE REVIEW

**Comment by rsriniva** [comment]
@jramcast - test for PR from fork. looks like the source repo checks in the GH actions work as suggested by you. This PR is to mention the version of RHOAI we tested with in the home page.

**Review by jramcast — APPROVED** [review]
LGTM.

I assume the condition that prevents HTML from rendering in fork PRs is this one right? https://github.com/RedHatQuickCourses/rhods-intro/blob/main/.github/workflows/pr.yml#L19

Also, we should apply the same condition to the other quick course repos.

**Comment by jramcast** [comment]
Consider rendering the HTML even if the PR comes from a fork. 
What we want to block is the publishing step.
Something like this maybe?

```
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Antora
        run: npm ci

      - name: Generate Site
        run: npm run build

      - name: Publish PR preview to GitHub Pages
        if: ${{ ! github.event.pull_request.head.repo.fork }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/site
```

**Comment by jramcast** [comment]
UPDATE: @rsriniva  please see https://github.com/RedHatQuickCourses/rhods-model/issues/7, I have applied the fork condition at the step level so only the publish step is ignored.

**Comment by rsriniva** [comment]
excellent suggestion @jramcast! I approved your changes and test PRs

**Comment by rsriniva** [comment]
applied your if: block suggestion to this repo. thanks!

**Pull request merged**
